version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ubuntu/deployment/target
permissions:
  - object: restart-after-deploy.sh
    pattern: 755
hooks:
  ApplicationStart:
    - location: restart-after-deploy.sh
      timeout: 300