image: maven:latest
pipelines:
  custom:
    manual-check:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -B verify --file pom.xml
          after-script:
            - pipe: atlassian/checkstyle-report:0.3.0
      - step:
          name: Security Scan
          script:
            - pipe: atlassian/git-secrets-scan:0.5.1
    manual-dev-push:
      - step:
          name: Build and Deploy
          script:
            - apt-get update && apt-get install -y openssh-client
            - echo "Building the application..."
            - mvn clean install
            - echo "Application built successfully!"
            - echo "Preparing deployment package..."
            - pwd
            - ls -l target
            - tar -czvf deploy-package.tar.gz -C target .
            - ls -l target
            - echo "Deployment package prepared!"
            - echo "Deploying to server..."
            - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            - cat ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa
            - ssh-keyscan ec2-13-53-41-209.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts
            - scp deploy-package.zip ec2-13-53-41-209.eu-north-1.compute.amazonaws.com:/deployment
            - ssh ec2-13-53-41-209.eu-north-1.compute.amazonaws.com 'unzip -o /deployment/deploy-package.zip -d /deployment'
            # - ssh ec2-13-53-41-209.eu-north-1.compute.amazonaws.com 'systemctl restart your-app-service'
            # - echo "Application deployed successfully!"