image: maven:latest
pipelines:
  custom:
    manual-check:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -B verify --file pom.xml
          after-script:
            - pipe: atlassian/checkstyle-report:0.3.0
      - step:
          name: Security Scan
          script:
            - pipe: atlassian/git-secrets-scan:0.5.1