pipelines:
  custom:
    manual-check:
      - step:
          image: maven:3.6.3-openjdk-11-slim
          name: Build and Test
          caches:
            - maven
          script:
            - mvn clean install