image: maven:latest
pipelines:
  custom:
    manual-check:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -B verify --file pom.xml
          after-script:
            - pipe: atlassian/checkstyle-report:0.3.0
      - step:
          name: Security Scan
          script:
            - pipe: atlassian/git-secrets-scan:0.5.1
    manual-dev-push:
      - step:
          name: Build and Deploy
          script:
            - apt-get update && apt-get install -y openssh-client
            - echo "Building the application..."
            - mvn clean install
            - echo "Application built successfully!"
            - echo "Preparing deployment package..."
            - pwd
            - ls -l target
            - tar -czvf deploy-package.tar.gz -C target .
            - ls -l target
            - echo "Deployment package prepared!"
            - echo "Deploying to server..."
            - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
            - chmod 600 ~/.ssh/id_rsa
            - sudo apt-get install openssh-client
            - ssh-keyscan ec2-16-171-142-151.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts
            # - scp deploy-package.zip user@your-server-ip:/path/to/deployment
            # - ssh user@your-server-ip 'unzip -o /path/to/deployment/deploy-package.zip -d /path/to/deployment'
            # - ssh user@your-server-ip 'systemctl restart your-app-service'
            # - echo "Application deployed successfully!"