image: maven:latest
pipelines:
  custom:
    manual-check:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -B verify --file pom.xml
          after-script:
            - pipe: atlassian/checkstyle-report:0.3.0
      - step:
          name: Security Scan
          script:
            - pipe: atlassian/git-secrets-scan:0.5.1
    manual-dev-push:
      - step:
          name: Build and Deploy
          deployment: Dev
          script:
          - apt-get update
          - apt-get install -y zip
          - echo "Building the application..."
          - mvn clean install
          - cd target
          - cp /../appspec.yml target/
          - ls -l
          - zip -r test.ZIP .
          - pipe: atlassian/aws-code-deploy:0.2.5
            variables:
              AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
              AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
              AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
              APPLICATION_NAME: ${APPLICATION_NAME}
              S3_BUCKET: ${S3_BUCKET}
              COMMAND: 'upload'
              ZIP_FILE: 'test.ZIP'
              DEBUG: 'true'
          - pipe: atlassian/aws-code-deploy:0.2.5
            variables:
              AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
              AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
              AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
              COMMAND: 'deploy'
              APPLICATION_NAME: ${APPLICATION_NAME}
              DEPLOYMENT_GROUP: ${DEPLOYMENT_GROUP}
              IGNORE_APPLICATION_STOP_FAILURES: 'true'
              FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
              S3_BUCKET: ${S3_BUCKET}
              WAIT: 'true'
              DEBUG: 'true'