pipelines:
  custom:
    manual-check:
      - step:
          image: maven:latest
          name: Build and Test
          caches:
            - maven
          script:
            - mvn -version
            - mvn clean install