spring:
  datasource:
    url: jdbc:mysql://2.57.137.47:3306/strefainf_db
    username: strefainf_db
    password: IaTK5M3GMx
  http:
    message:
      converters:
        preferred-json-mapper: jackson
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


